Upgrade spotbugs-maven-plugin:4.7.3.4 -> 4.8.2.0
Fixes spotbugs when run with Java 21, otherwise getting

```
Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.7.3.4:spotbugs failed:
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be
removed in a future release
```